name: Playwright Tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: [main, master]
jobs:
  test-e2e:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build NextJS App
        run: pnpm build:ci
      - name: Run Playwright tests
        run: pnpm test:e2e:ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  # test-unit:
  #   timeout-minutes: 5
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '16.x'
  #   - name: Install dependencies
  #     run: yarn
  #   - name: Run unit tests
  #     run: yarn test run
